# Generated by Django 3.1 on 2020-08-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200823_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
